### ISSUE TITLE
Collector error in live filter pipeline after client disconnect.

### ISSUE THREAD

**Issue by natemago** [theia-log/theia#14]
Closing of client websocket connection is not handled properly in the live event pipeline - the collector throws an exception about the connction being closed (which it is):
```
Traceback (most recent call last):
  File "/home/pavle/projects/theia/theia/theia/collector.py", line 96, in pipe
    await ws.send(result)
  File "/home/pavle/projects/theia/theia/ENV/dev/lib/python3.6/site-packages/websockets/protocol.py", line 363, in send
    yield from self.ensure_open()
  File "/home/pavle/projects/theia/theia/ENV/dev/lib/python3.6/site-packages/websockets/protocol.py", line 503, in ensure_open
    self.close_code, self.close_reason) from self.transfer_data_exc
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006 (connection closed abnormally [internal]), no reason
```

The LiveFilter associated with this websocket must be removed once the connection is closed.

**Comment by natemago** [comment]
Fixed.
